#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0  ]; then echo "[$0] $@"; fi; }

GOTIFY_HOME="${GOTIFY_HOME:-/gotify}";
GOTIFY_CONFIG="${GOTIFY_CONFIG:-/etc/gotify/config.yml}"; # or /gotify/config.yml
GOTIFY_DATA="${GOTIFY_DATA:-/gotify/data}";

vecho "Ensure configuration directories exist";
mkdir -p \
    ${GOTIFY_HOME} \
    $(dirname $GOTIFY_CONFIG) \
    ${GOTIFY_DATA}/certs \
    ${GOTIFY_PLUGINSDIR:-$GOTIFY_DATA/plugins} \
    ${GOTIFY_UPLOADEDIMAGESDIR:-$GOTIFY_DATA/images} \
    ;

# ensure gotify config.yml exists
if [ ! -f "${GOTIFY_CONFIG}" ];
then
    vecho "Setting up default configuration at ${GOTIFY_CONFIG}";
    cp /defaults/config.yml ${GOTIFY_CONFIG};
# else
#     vecho 'Found configurations at ${GOTIFY_CONFIG}';
fi;

vecho "Fixing permissions";
chown -R ${S6_USER:-alpine}:${PGID:-1000} \
    ${GOTIFY_HOME} \
    $(dirname ${GOTIFY_CONFIG}) \
    ${GOTIFY_DATA} \
    ;
