#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0  ]; then echo "[$0] $@"; fi; }

GOTIFY_CONFIG="${GOTIFY_CONFIG:-/etc/gotify/config.yml}"; # or /gotify/config.yml
GOTIFY_DATA="${GOTIFY_DATA:-/gotify/data}";

vecho "Ensure configuration directories exist";
mkdir -p \
    $(dirname $GOTIFY_CONFIG) \
    ${GOTIFY_DATA}/certs \
    ${GOTIFY_PLUGINSDIR:-$GOTIFY_DATA/plugins} \
    ${GOTIFY_UPLOADEDIMAGESDIR:-$GOTIFY_DATA/images} \
    ;

# function to substitute paths in config files
_subst () {
    sed \
    -e "s|GOTIFY_DATA|${GOTIFY_DATA}|g" \
    -e "s|GOTIFY_PLUGINSDIR|${GOTIFY_PLUGINSDIR}|g" \
    -e "s|GOTIFY_SERVER_PORT|${GOTIFY_SERVER_PORT:-80}|g" \
    -e "s|GOTIFY_UPLOADEDIMAGESDIR|${GOTIFY_UPLOADEDIMAGESDIR}|g" \
    $1 > $2;
}

# ensure gotify config.yml exists
if [ ! -f "${GOTIFY_CONFIG}" ];
then
    vecho "Setting up default configuration at ${GOTIFY_CONFIG}";
    _subst /defaults/config.yml "${GOTIFY_CONFIG}";
fi;

# fix permissions
if [ -z "${GOTIFY_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown -R ${S6_USER:-alpine}:${PGID:-1000} \
        $(dirname ${GOTIFY_CONFIG}) \
        "${GOTIFY_DATA}" \
        ;
fi;
